Repository UQcsse3200/2023-studio-3, pull requests merged in 2023-08, with the labels that each got.

#41 Add Projectile Base Mechanics to Main
  source/core/assets/configs/NPCs.json
  source/core/assets/images/projectile.png
  source/core/assets/sounds/projectile firing.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/TrajectTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
Labels: team 1, sprint 1

#44 Merging changes from main into team 2
  source/core/assets/configs/NPCs.json
  source/core/assets/images/projectile.png
  source/core/assets/sounds/projectile firing.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/TrajectTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
Labels: team 2, sprint 1

#49 Revert "Revert "Updated comments""
  README.md
  source/core/assets/configs/tower.json
  source/core/assets/images/turret.atlas
  source/core/assets/images/turret.png
  source/core/assets/images/turret01.atlas
  source/core/assets/images/turret01.png
  source/core/assets/images/turret_deployed.png
  source/core/assets/test/files/turret01.atlas
  source/core/assets/test/files/turret01.png
  source/core/assets/test/files/turret_deployed.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CostComponent.java
  source/core/src/main/com/csse3200/game/components/popupmenu/PopupMenuInputComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerIdleTask.java
  source/core/src/main/com/csse3200/game/components/tower/TowerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/configs/WallTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/baseTowerConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TowerFactory.java
  source/core/src/test/com/csse3200/game/components/CostComponentTest.java
  source/core/src/test/com/csse3200/game/components/popupmenu/PopupMenuInputComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: help wanted, team 2, sprint 1

#55 new tower sfx added and updated animation controller to play sounds
  source/core/assets/sounds/deploy.mp3
  source/core/assets/sounds/stow.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tower/TowerAnimationController.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: team 2, sprint 1

#56 Towers' sound assets and further feature implementations
  source/core/assets/images/wall.png
  source/core/assets/images/wallTower.png
  source/core/assets/sounds/Sci-Fi 1.ogg
  source/core/assets/sounds/deploy.mp3
  source/core/assets/sounds/gun_shot_trimmed.mp3
  source/core/assets/sounds/stow.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tower/TowerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/TowerFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: team 2, sprint 1

#65 Team 2 towers incorporating projectile firing
  source/core/assets/images/wall.png
  source/core/assets/sounds/Sci-Fi 1.ogg
  source/core/assets/sounds/gun_shot_trimmed.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CostComponent.java
  source/core/src/main/com/csse3200/game/components/popupmenu/PopupMenuInputComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerIdleTask.java
  source/core/src/main/com/csse3200/game/components/tower/TowerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/TowerFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: team 2, sprint 1
