Repository UQcsse3200/2023-studio-3, pull requests merged in 2023-10, with the labels that each got.

#198 Team 2 UI alasdair
  source/core/assets/configs/text.json
  source/core/assets/images/ui/Button_Bg.png
  source/core/assets/images/ui/font.fnt
  source/core/assets/images/ui/font.png
  source/core/assets/images/ui/mouse_effect.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGamePauseDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuContinueButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuMainMenuButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuPlanetSelectButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuSettingsButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuTimeStopComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PauseMenuFactory.java
  source/core/src/main/com/csse3200/game/screens/AssetLoader.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/ui/ButtonFactory.java
Labels: enhancement, task, team 2, sprint 3

#202 Mohamad maps
  source/core/assets/images/GrassTile/grass_tile_1.png
  source/core/assets/images/GrassTile/grass_tile_2.png
  source/core/assets/images/GrassTile/grass_tile_3.png
  source/core/assets/images/GrassTile/grass_tile_4.png
  source/core/assets/images/GrassTile/grass_tile_5.png
  source/core/assets/images/GrassTile/grass_tile_6.png
  source/core/assets/images/GrassTile/grass_tile_7.png
  source/core/assets/images/grass_2.png
  source/core/assets/images/highlight_tile.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/LevelWaves.java
  source/core/src/main/com/csse3200/game/components/tower/TNTDamageComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/TowerFactory.java
  source/core/src/main/com/csse3200/game/screens/DesertGameScreen.java
  source/core/src/main/com/csse3200/game/screens/IceGameScreen.java
  source/core/src/main/com/csse3200/game/screens/LavaGameScreen.java
  source/core/src/main/com/csse3200/game/screens/LevelSelectScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/MapService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainFactoryTest.java
  source/core/src/test/com/csse3200/game/services/MapServiceTest.java
Labels: enhancement, feature, team 2, sprint 3

#209 Merging shivam-ui-elements to team-2-ui
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/WaveService.java
  source/core/src/test/com/csse3200/game/components/maingame/UIElementsDisplayTest.java
Labels: enhancement, feature, sprint 3

#214 Team 1 Mobs Enhancement merge to main (bug fixes)
  source/core/src/main/com/csse3200/game/components/tasks/MobMeleeAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MobRangedAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bosstask/DemonBossTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bosstask/IceBabyTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bosstask/PatrickTask.java
  source/core/src/main/com/csse3200/game/entities/factories/WaveFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/WaveFactoryTest.java
Labels: team 1, sprint 3

#219 Team 2 Sound
  source/core/src/main/com/csse3200/game/screens/LevelSelectScreen.java
  source/core/src/main/com/csse3200/game/screens/StoryScreen.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
  source/core/src/test/com/csse3200/game/input/BuildInputComponentTest.java
Labels: task, sprint 3

#222 Bug fix for TurretSelectScreen
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
Labels: bug

#234 Build Tower bug fix
  source/core/src/main/com/csse3200/game/entities/EntityService.java
Labels: bug, enhancement, team 2, sprint 4

#246 Team 7 tower stat alterations
  source/core/src/main/com/csse3200/game/components/tasks/CurrencyTask.java
  source/core/src/main/com/csse3200/game/components/tasks/DroidCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireworksTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PierceTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RicochetTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StunTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WallTowerDestructionTask.java
  source/core/src/main/com/csse3200/game/components/tower/DroidAnimationController.java
  source/core/src/main/com/csse3200/game/entities/configs/IncomeTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/TowerFactory.java
Labels: team 7, sprint 4

#248 Team 2 ahmad - control improvements
  source/core/src/main/com/csse3200/game/components/gamearea/CurrencyDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/input/BuildInputComponent.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
  source/core/src/main/com/csse3200/game/services/CurrencyService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/UIComponent.java
  source/core/src/test/com/csse3200/game/input/BuildInputComponentTest.java
Labels: task, team 2, sprint 4

#249 Team 4 waves
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/WaveTask.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/WaveService.java
Labels: enhancement, team 4, sprint 4

#255 Team 2 UI alasdair
  source/core/assets/images/ui/Logo2.png
  source/core/assets/images/ui/MainLogo.png
  source/core/assets/images/ui/font.fnt
  source/core/assets/images/ui/font.png
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuButtonComponent.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuMainMenuButton.java
  source/core/src/main/com/csse3200/game/entities/factories/PauseMenuFactory.java
  source/core/src/main/com/csse3200/game/ui/ButtonFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/PauseMenuFactoryTest.java
Labels: sprint 4

#256 Mohamad juice
  source/core/assets/images/green_tile.png
  source/core/assets/images/red_tile.png
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/rendering/CameraShaker.java
  source/core/src/main/com/csse3200/game/screens/AssetLoader.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/MapService.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
Labels: enhancement, feature, team 2, sprint 4

#257 merging shivam-ui-elements to team-2-ui
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
Labels: task

#258 Team 2 UI - Progress merge
  source/core/assets/images/green_tile.png
  source/core/assets/images/red_tile.png
  source/core/assets/images/ui/Logo2.png
  source/core/assets/images/ui/MainLogo.png
  source/core/assets/images/ui/buttons/Emulogic-zrEw.fnt
  source/core/assets/images/ui/buttons/determination_mono_18.fnt
  source/core/assets/images/ui/buttons/determination_mono_18_bold.fnt
  source/core/assets/images/ui/buttons/determination_mono_32.fnt
  source/core/assets/images/ui/buttons/determination_mono_48_title.fnt
  source/core/assets/images/ui/buttons/emulogic_18.fnt
  source/core/assets/images/ui/buttons/game_paused_24.fnt
  source/core/assets/images/ui/buttons/game_paused_title.fnt
  source/core/assets/images/ui/buttons/glass.atlas
  source/core/assets/images/ui/buttons/glass.json
  source/core/assets/images/ui/buttons/glass.png
  source/core/assets/images/ui/buttons/glitch_24.fnt
  source/core/assets/images/ui/buttons/glitch_title.fnt
  source/core/assets/images/ui/font.fnt
  source/core/assets/images/ui/font.png
  source/core/assets/sounds/ui/click/click_01.ogg
  source/core/assets/sounds/ui/hover/hover_01.ogg
  source/core/assets/sounds/ui/open_close/close_01.ogg
  source/core/assets/sounds/ui/open_close/open_01.ogg
  source/core/assets/sounds/ui/switch/switch_01.ogg
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/components/gamearea/CurrencyDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/EngineerCountDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameLoseDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGamePauseDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuButtonComponent.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuContinueButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuMainMenuButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuPlanetSelectButton.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuSettingsButton.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PauseMenuFactory.java
  source/core/src/main/com/csse3200/game/input/BuildInputComponent.java
  source/core/src/main/com/csse3200/game/rendering/CameraShaker.java
  source/core/src/main/com/csse3200/game/screens/AssetLoader.java
  source/core/src/main/com/csse3200/game/screens/HelpScreen.java
  source/core/src/main/com/csse3200/game/screens/LevelSelectScreen.java
  source/core/src/main/com/csse3200/game/screens/LosingScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/StoryScreen.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
  source/core/src/main/com/csse3200/game/services/GameEndService.java
  source/core/src/main/com/csse3200/game/services/MapService.java
  source/core/src/main/com/csse3200/game/ui/ButtonFactory.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PauseMenuFactoryTest.java
  source/core/src/test/com/csse3200/game/input/BuildInputComponentTest.java
  source/core/src/test/com/csse3200/game/rendering/CameraShakerTest.java
Labels: enhancement, team 2, sprint 4

#263 Team 7 tower stat alterations
  source/core/assets/configs/tower.json
  source/core/src/main/com/csse3200/game/components/tasks/CurrencyTask.java
  source/core/src/main/com/csse3200/game/input/UpgradeUIComponent.java
  source/core/src/main/com/csse3200/game/screens/TowerType.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: team 7, sprint 4

#264 Code smells
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainGrid.java
  source/core/src/main/com/csse3200/game/components/tasks/DroidCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TNTTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tower/DroidAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/TNTDamageComponent.java
  source/core/src/main/com/csse3200/game/rendering/CameraShaker.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/tasks/DroidCombatTaskTest.java
  source/core/src/test/com/csse3200/game/rendering/CameraShakerTest.java
Labels: documentation, team 2, sprint 4

#265 Feature/team4/wave adjustments
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/npc/SplitMoblings.java
  source/core/src/main/com/csse3200/game/components/tasks/MobTask/MobTask.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/LevelWaves.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/Tuple.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/WaveTask.java
  source/core/src/main/com/csse3200/game/entities/factories/WaveFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/WaveService.java
  source/core/src/test/com/csse3200/game/entities/factories/WaveFactoryTest.java
Labels: enhancement, team 4, sprint 4

#268 Team 2 progress merge
  source/core/assets/images/ui/buttons/determination_mono_22.fnt
  source/core/assets/images/ui/buttons/glass.atlas
  source/core/assets/images/ui/buttons/glass.json
  source/core/assets/images/ui/buttons/glass.png
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/human/EngineerCombatTask.java
  source/core/src/main/com/csse3200/game/input/BuildInputComponent.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/screens/LevelSelectScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TowerType.java
  source/core/src/test/com/csse3200/game/components/tasks/EngineerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
  source/core/src/test/com/csse3200/game/input/BuildInputComponentTest.java
Labels: team 2, sprint 4

#269 Team 2 - merge to team branch
  source/core/src/main/com/csse3200/game/components/maingame/MainGameDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuButtonComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/GameEndService.java
  source/core/src/main/com/csse3200/game/services/GameTime.java
Labels: task, team 2

#270 Team 2 UI alasdair
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuButtonComponent.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuTimeStopComponent.java
  source/core/src/main/com/csse3200/game/services/WaveService.java
  source/core/src/test/com/csse3200/game/components/pausemenu/PauseMenuTimeStopComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PauseMenuFactoryTest.java
Labels: team 2, sprint 4

#274 Team 2 ahmad
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/GameTime.java
Labels: team 2, sprint 4

#276 Mohamad juice
  source/core/src/main/com/csse3200/game/components/maingame/LevelProgressBar.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/WaveFactory.java
Labels: enhancement, team 2, sprint 4

#278 Fix code smells for the towers task
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/DroidCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireworksTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PierceTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RicochetTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StunTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TNTTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/test/com/csse3200/game/components/tasks/DroidCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FireTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FireworksTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PierceTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RicochetTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/StunTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TNTTowerCombatTaskTest.java
Labels: team 7

#279 Team 5 Added new turrets to turret select screen
  source/core/assets/images/spanner.png
  source/core/assets/images/turret-select/droid-tower-selected.png
  source/core/assets/images/turret-select/fire-tower-clicked.png
  source/core/assets/images/turret-select/fire-tower-selected.png
  source/core/assets/images/turret-select/firework-tower-default.png
  source/core/assets/images/turret-select/firework-tower-selected.png
  source/core/assets/images/turret-select/mine-tower-selected.png
  source/core/assets/images/turret-select/pierce-tower-default.png
  source/core/assets/images/turret-select/pierce-tower-selected.png
  source/core/assets/images/turret-select/ricochet-tower-default.png
  source/core/assets/images/turret-select/ricochet-tower-selected.png
  source/core/assets/images/turret-select/stun-tower-selected.png
  source/core/assets/images/turret-select/tnt-tower-selected.png
  source/core/assets/images/turret-select/wall-tower-default.png
  source/core/assets/images/turret-select/wall-tower-selected.png
  source/core/assets/images/turret-select/weapon-tower-selected.png
  source/core/src/main/com/csse3200/game/input/BuildInputComponent.java
  source/core/src/main/com/csse3200/game/input/UpgradeUIComponent.java
  source/core/src/main/com/csse3200/game/screens/TowerType.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
Labels: team 5, sprint 4

#280 Team 7 tower stat alterations
  source/core/src/main/com/csse3200/game/components/tasks/FireTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PierceTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RicochetTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StunTowerCombatTask.java
Labels: team 7, sprint 4

#283 Team 2 ahmad - new tower skin fixes
  source/core/assets/images/spanner.png
  source/core/assets/images/turret-select/droid-tower-selected.png
  source/core/assets/images/turret-select/fire-tower-clicked.png
  source/core/assets/images/turret-select/fire-tower-selected.png
  source/core/assets/images/turret-select/firework-tower-default.png
  source/core/assets/images/turret-select/firework-tower-selected.png
  source/core/assets/images/turret-select/mine-tower-selected.png
  source/core/assets/images/turret-select/pierce-tower-default.png
  source/core/assets/images/turret-select/pierce-tower-selected.png
  source/core/assets/images/turret-select/ricochet-tower-default.png
  source/core/assets/images/turret-select/ricochet-tower-selected.png
  source/core/assets/images/turret-select/stun-tower-selected.png
  source/core/assets/images/turret-select/tnt-tower-selected.png
  source/core/assets/images/turret-select/wall-tower-default.png
  source/core/assets/images/turret-select/wall-tower-selected.png
  source/core/assets/images/turret-select/weapon-tower-selected.png
  source/core/assets/images/ui/buttons/glass.atlas
  source/core/assets/images/ui/buttons/glass.json
  source/core/assets/images/ui/buttons/glass.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/gamearea/CurrencyDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/EngineerCountDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuButtonComponent.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuTimeStopComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/DroidCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireworksTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MobAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MobDeathTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MobTask/MobTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PierceTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RicochetTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/SpawnWaveTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StunTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TNTTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/WaveClass.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/WaveTask.java
  source/core/src/main/com/csse3200/game/entities/factories/WaveFactory.java
  source/core/src/main/com/csse3200/game/input/BuildInputComponent.java
  source/core/src/main/com/csse3200/game/input/UpgradeUIComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/TowerType.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
  source/core/src/test/com/csse3200/game/components/tasks/DroidCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FireTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FireworksTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PierceTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RicochetTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/StunTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TNTTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/WaveFactoryTest.java
Labels: bug

#282 Team 4 Bug Fixes & Code Smell Fixes
  source/core/src/main/com/csse3200/game/components/npc/SplitMoblings.java
  source/core/src/main/com/csse3200/game/components/tasks/SpawnWaveTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bosstask/IceBabyTask.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/LevelWaves.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/WaveClass.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/WaveTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/components/SplitMoblingsTest.java
  source/core/src/test/com/csse3200/game/components/tasks/SpawnWaveTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/WaveFactoryTest.java
Labels: team 4, sprint 4

#285 Team 1 Quality of Life changes to mobs
  source/core/assets/images/mobs/skeleton.atlas
  source/core/assets/images/mobs/skeleton.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/EffectsComponent.java
  source/core/src/main/com/csse3200/game/components/gamearea/EngineerCountDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/ArcaneArcherAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/CoatAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/DodgingComponent.java
  source/core/src/main/com/csse3200/game/components/npc/DragonKnightAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/FireWormAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/FirewizardAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/NecromancerAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/NightBorneAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/RockyAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/SkeletonAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/WaterQueenAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/WaterSlimeAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/WizardAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/MobTask/MobTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/WaveFactory.java
  source/core/src/test/com/csse3200/game/components/SplitMoblingsTest.java
Labels: enhancement, team 1, sprint 4

#284 Team7 sounds - added new sounds for the towers
  source/core/assets/sounds/towers/12-Gauge-Pump-Action-Shotgun-Close-Gunshot.mp3
  source/core/assets/sounds/towers/5.56_single_shot.mp3
  source/core/assets/sounds/towers/Desert-Eagle-Far-Single-Gunshot.mp3
  source/core/assets/sounds/towers/ar15_single_shot_far.mp3
  source/core/assets/sounds/towers/eco_tower_ping.mp3
  source/core/assets/sounds/towers/explosion.mp3
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tower/DroidAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/EconTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/FireTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/FireworksTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/PierceTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/RicochetTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/StunTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/TNTAnimationController.java
  source/core/src/test/com/csse3200/game/components/tower/DroidAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/FireTowerAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/StunTowerAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/TNTAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: sprint 4

#286 Team 2 UI - Fix for new towers causing game to crash
  source/core/assets/images/ui/buttons/glass.atlas
  source/core/assets/images/ui/buttons/glass.json
  source/core/assets/images/ui/buttons/glass.png
  source/core/src/main/com/csse3200/game/components/gamearea/CurrencyDisplay.java
  source/core/src/main/com/csse3200/game/components/gamearea/EngineerCountDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/UIElementsDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuButtonComponent.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuTimeStopComponent.java
  source/core/src/main/com/csse3200/game/components/popupmenu/PopupMenuInputComponent.java
  source/core/src/main/com/csse3200/game/components/tower/TowerUpgraderComponent.java
  source/core/src/main/com/csse3200/game/input/BuildInputComponent.java
  source/core/src/main/com/csse3200/game/screens/TowerType.java
  source/core/src/test/com/csse3200/game/components/pausemenu/PauseMenuTimeStopComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PauseMenuFactoryTest.java
  source/core/src/test/com/csse3200/game/input/BuildInputComponentTest.java
Labels: bug, team 2, sprint 4

#298 Team 4 - Waves - Final Code Smell Fixes & New Tests for WaveService Added.
  source/core/src/main/com/csse3200/game/entities/factories/WaveFactory.java
  source/core/src/test/com/csse3200/game/services/WaveServiceTest.java
Labels: team 4, sprint 4

#297 Team 7 - Fix code smells for the towers
  source/core/src/main/com/csse3200/game/components/tasks/DroidCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FireTowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TowerCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WallTowerDestructionTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bombship/BombshipCombatTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bombship/BombshipWanderTask.java
  source/core/src/main/com/csse3200/game/components/tower/FireTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/StunTowerAnimationController.java
  source/core/src/main/com/csse3200/game/components/tower/TowerUpgraderComponent.java
  source/core/src/main/com/csse3200/game/components/tower/WallTowerAnimationController.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseTowerConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/DroidTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/FireTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/FireworksTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/HealTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/IncomeTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/PierceTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/RicochetTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/StunTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/TNTTowerConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/WallTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponTowerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/baseTowerConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/BombshipFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TowerFactory.java
  source/core/src/test/com/csse3200/game/components/tasks/DroidCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FireTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FireworksTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PierceTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RicochetTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/StunTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TNTTowerCombatTaskTest.java
  source/core/src/test/com/csse3200/game/components/tower/DroidAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/FireTowerAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/StunTowerAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/TNTAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tower/TNTDamageComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TowerFactoryTest.java
Labels: team 7, sprint 4

#299 [Team 4] Incorrect end of game trigger issue
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: team 4, sprint 4

#300 Team 1 Mobs & Projectile Bug fixes
  source/core/src/main/com/csse3200/game/components/npc/DeflectingComponent.java
  source/core/src/main/com/csse3200/game/components/npc/DodgingComponent.java
  source/core/src/main/com/csse3200/game/components/npc/SplitMoblings.java
  source/core/src/main/com/csse3200/game/components/npc/WizardAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/MobTask/MobTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bosstask/IceBabyTask.java
  source/core/src/main/com/csse3200/game/components/tasks/bosstask/PatrickTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: task, team 1, sprint 4

#305 Team 5 Added click sounds, updated tower descriptions and their fonts
  source/core/src/main/com/csse3200/game/screens/TowerType.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
Labels: team 5, sprint 4

#306 Post sprint bug fixes for showcasing
  source/core/src/main/com/csse3200/game/components/tasks/MobTask/MobTask.java
  source/core/src/main/com/csse3200/game/components/tasks/waves/LevelWaves.java
  source/core/src/main/com/csse3200/game/screens/HelpScreen/Tutorial.java
  source/core/src/main/com/csse3200/game/screens/LevelSelectScreen.java
  source/core/src/main/com/csse3200/game/screens/StoryScreen.java
  source/core/src/main/com/csse3200/game/screens/TurretSelectionScreen.java
Labels: enhancement
